### ISSUE TITLE
训练不收敛

### ISSUE THREAD

**Issue by hjgw** [AstarLight/Lets_OCR#14]
作者您好，请问一下，您训练多少个epoch开始收敛呢？我用您提供的数据集训练2个epoch还是震荡的，用您的代码转换了ICDAR2017的数据集训练，训练了7个epoch也不收敛。想问下您除了调整学习速率还有什么解决办法吗？谢谢～

**Comment by AstarLight** [comment]
我这边大概一个epoch loss就开始下降，大概4,5个epoch开始收敛

**Comment by maichm** [comment]
@AstarLight 训练速度很慢，tag_anchor函数最好优化一下？

**Comment by leonzhu211** [comment]
我用自己的数据，train loss 跑一个晚上，大概到 0.07，但 infer 的效果看起来一般

**Comment by AstarLight** [comment]
@leonzhu211 是不是recall较好，precision较差？我不知道你的数据是什么样的，但是CTPN这个算法只对水平文本有较好效果

**Comment by huazai-1994** [comment]
@AstarLight 请问如果是垂直文本应该怎么调整ctpn的参数？

**Comment by QQ1696311291** [comment]
训练不收敛，损失一直是0.7左右？有人遇到这个问题吗？求解决办法

**Comment by youngyoung611** [comment]
训练不收敛+1....基本上跑了一整天才跑了9个epoch，求解决方法呀~~

**Comment by RuiChen520** [comment]
请问一下，您是怎样切分数据集的呢？代码描述上您是使用俩个数据集，但是从csdn您的训练截图来看，您好像只使用了msra数据集？

**Comment by GanWang** [comment]
跑了一整天才跑了3个epoch，路过

**Comment by ShangLe0607** [comment]
请问我的出现这个错误是什么问题呢[0/20][20/282] Loss: 42.145580
[0/20][40/282] Loss: 19.428555
[0/20][60/282] Loss: 17.523825
[0/20][80/282] Loss: 16.701580
[0/20][100/282] Loss: 16.425825
[0/20][120/282] Loss: 16.065802
[0/20][140/282] Loss: 15.806343
[0/20][160/282] Loss: 15.621722
[0/20][180/282] Loss: 15.718269
[0/20][200/282] Loss: 15.642500
[0/20][220/282] Loss: 15.453972
[0/20][240/282] Loss: 15.550603
[0/20][260/282] Loss: 15.239004
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    cost = trainBatch(net, criterion, optimizer, train_iter)
  File "train.py", line 76, in trainBatch
    t, l = converter.encode(cpu_texts)
  File "/opt/crnn/lib/convert.py", line 47, in encode
    index = self.dict[char]
KeyError: '\ufeff'

**Comment by leahyyy** [comment]
> 作者您好，请问一下，您训练多少个epoch开始收敛呢？我用您提供的数据集训练2个epoch还是震荡的，用您的代码转换了ICDAR2017的数据集训练，训练了7个epoch也不收敛。想问下您除了调整学习速率还有什么解决办法吗？谢谢～

你好，我也是在跑ICDAR这个数据集，我把文字都切出来了，但是尺寸都不一样大小，请问一下用作者的CRNN的时候需要怎样调整输入图像的大小呢？
