### ISSUE TITLE
在CRNN 中训练数据时 RuntimeError: DataLoader worker (pid 2918) exited unexpectedly with exit code 1

### ISSUE THREAD

**Issue by fanruifeng** [AstarLight/Lets_OCR#46]
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    cost = trainBatch(net, criterion, optimizer, train_iter)
  File "train.py", line 70, in trainBatch
    data = train_iter.next()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 280, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 259, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 343, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 178, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2918) exited unexpectedly with exit code 1.
这种错 如何解决呢

**Comment by fh520pzx** [comment]
一样的问题啊

**Comment by 18824156643** [comment]
老哥这个问题你解决了吗

**Comment by chenshihao123456** [comment]
解决了吗，我也遇到了

**Comment by chenshihao123456** [comment]
我也遇到了，如何解决？
