### ISSUE TITLE
RuntimeError: set_sizes_contiguous is not allowed on Tensor created from .data or .detach()

### ISSUE THREAD

**Issue by wjx-git** [AstarLight/Lets_OCR#57]
Traceback (most recent call last):
  File "/home/ayg/Downloads/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/ayg/Downloads/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/ayg/Downloads/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ayg/Downloads/pycharm-2019.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/ayg/workspace/crnn/train.py", line 163, in <module>
    cost = trainBatch(net, criterion, optimizer, train_iter)
  File "/home/ayg/workspace/crnn/train.py", line 73, in trainBatch
    lib.dataset.loadData(image, cpu_images)
  File "/home/ayg/workspace/crnn/lib/dataset.py", line 144, in loadData
    v.data.resize_(data.size()).copy_(data)
RuntimeError: set_sizes_contiguous is not allowed on Tensor created from .data or .detach()

程序运行到这里出错：
def loadData(v, data):
    v.data.resize_(data.size()).copy_(data)

**Comment by wjx-git** [comment]
找到一个解决方法：
http://www.iterate.site/post/01-%E6%95%B0%E5%AD%97%E7%9A%84%E5%BC%A0%E5%8A%9B/02-%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0/02-%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8/10-%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%E6%A1%86%E6%9E%B6/01-pytorch/error-set_sizes_contiguous-is-not-allowed-on-tensor-created-from-data/

楼主是说Pytorch版本问题，最新1.1.0版本会出现这种问题。
代码改成如下即可：
with torch.no_grad():
        v.resize_(data.size()).copy_(data)
