### ISSUE TITLE
module 'lib.nms' has no attribute 'cpu_nms'

### ISSUE THREAD

**Issue by Lie-huo** [AstarLight/Lets_OCR#85]
编译后遇到这样的问题
Traceback (most recent call last):
  File "infer.py", line 356, in <module>
    infer_one(url, net)
  File "infer.py", line 241, in infer_one
    nms_result = lib.nms.cpu_nms(for_nms, NMS_THRESH)
AttributeError: module 'lib.nms' has no attribute 'cpu_nms'

**Comment by maggie-c1523** [comment]
你编译有成功嘛？在Lib底下有生成nms.so的文件吗？
